### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by JannikStreek** [kitsteam/pictosearch#267]
**Describe the bug**
Sometimes the font is not displayed properly.

- Inside the the detail view of a pictogram, clicking on Text > Format 

The font seems to be not correct, see:

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/5bf41c52-147f-47a6-afc9-f8c87c3ded85" />

**Comment by mgaebler** [comment]
The current @font-face rules use text values (light, bold) which can cause issues. Replacing them with numeric values and using them explicitly in the text component will do the trick.

```css
css@font-face {
  font-family: FiraSans;
  font-weight: 300; /* Light */
  src: url("/assets/fonts/firasans/FiraSans-Light.otf") format("opentype");
}

@font-face {
  font-family: FiraSans;
  font-weight: 400; /* Regular */
  src: url("/assets/fonts/firasans/FiraSans-Regular.otf") format("opentype");
}

@font-face {
  font-family: FiraSans;
  font-weight: 700; /* Bold */
  src: url("/assets/fonts/firasans/FiraSans-Bold.otf") format("opentype");
}
```
